version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/django_project/HR-Management-System
hooks:
  BeforeInstall:
      - location: scripts/before_install.sh
  AfterInstall:
      - location: scripts/after_install.sh